### PR TITLE
feat: dry run support for contracts

### PR DESCRIPTION
**Pull request by peterwht**
instantiate fails when gas is low
Screenshot 2024-12-14 at 4 02 08 PM
instantiate succeeds
Screenshot 2024-12-14 at 4 02 14 PM
instantiate fails with duplicate contract
Screenshot 2024-12-14 at 4 07 39 PM
upload fails with insufficient funds
Screenshot 2024-12-14 at 4 10 07 PM
upload succeeds
Screenshot 2024-12-14 at 4 10 16 PM
call fails
Screenshot 2024-12-14 at 5 16 28 PM

### CODE REVIEW

**Review by AlexD10S — APPROVED** [review]
Looks nice! 
Does the Debug Message section provide any value, or should it be removed?

**Comment by evilrobot-01** [comment]
Can we wrap the dry-run in something like an [alert](https://preline.co/docs/alerts.html#bordered-styles) coupled with a [collapse](https://preline.co/docs/collapse.html).

Justification: I probably dont care about the dry-run most of the time, except when debugging or when it fails. Based on the screenshots, it adds a lot of noise which perhaps most of the time will be ignored.

**Comment by evilrobot-01** [comment]
Is it possible to do any minification on the HTML output? Its currently sitting at 0.5MB. I also see there are various .scale files included via PAPI - could these be replaced via dynamic calls to reduce the size footprint?

**Review by al3mart — COMMENTED** [review]
We could use the api to show any costs or deposits, like storage, in terms of the token instead of raw units.

**Comment by evilrobot-01** [comment]
> We could use the api to show any costs or deposits, like storage, in terms of the token instead of raw units.

+1

**Pull request merged**
